#!/bin/bash
VERSION_GIT=$(head -1 < VERSION)
echo "Building version $VERSION_GIT"
docker build -t registry.volte.io/opensips:$VERSION_GIT -f Dockerfile .
docker push registry.volte.io/opensips:$VERSION_GIT
docker tag registry.volte.io/opensips:$VERSION_GIT registry.volte.io/opensips:latest
docker push registry.volte.io/opensips:latest
